# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_DolSMgLqyxQBGgY2_wYQ3Xd9nNLTbHA
"""

import pandas as pd
df = pd.DataFrame({'Isim':[ 'Mushtariybonu', 'Bibifotima', 'Moxichexra', 'Madina', 'Hurixon', 'Nurmuhammad', 'Merojiddin', 'Shuhradjon', 'Shoyatbek', 'Olloyor', 'Kamron'],
                     'Familya':['Qadamova', 'Joraboyeva', 'Yusupaliyeva', 'Amakixonova', 'Joraboyeva', 'Jumanazarov', 'Baxtiyorjonov', 'Shamsiddinov', 'Maqsudov', 'Ashurboyev', 'Olimov'],
                      'Yoshi':['21', '19', '20', '19', '19', '19', '19', '19', '19', '19', '19'],
                      'Kursi':['2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2']
                     })
print(df)

df.to_excel('Bonucha.xlsx', index=False, sheet_name='Sheet1')